import type { AppSettings, JournalEntry, Mood, Tag } from "@/src/types";

export const COLORS = {
  background: "#0D0D0F",
  surface: "#1A1A1F",
  elevated: "#242429",
  primary: "#7C6AF7",
  secondary: "#A78BFA",
  success: "#4ADE80",
  text: "#F4F4F5",
  muted: "#A1A1AA",
  border: "#27272A",
  danger: "#F87171",
  mood: {
    happy: "#4ADE80",
    sad: "#60A5FA",
    anxious: "#F59E0B",
    grateful: "#A78BFA",
    angry: "#F87171",
    neutral: "#A1A1AA",
    tired: "#94A3B8",
  } as Record<Mood, string>,
};

export const PROMPTS = [
  "What felt heavy today, and what helped you carry it?",
  "What moment today made you feel most alive?",
  "If tomorrow could feel 1% better, what would you change?",
] as const;

export const DEFAULT_TAGS: Tag[] = [
  { id: "gratitude", label: "gratitude", color: "#A78BFA" },
  { id: "work", label: "work", color: "#60A5FA" },
  { id: "family", label: "family", color: "#4ADE80" },
  { id: "health", label: "health", color: "#34D399" },
  { id: "growth", label: "growth", color: "#F59E0B" },
  { id: "anxiety", label: "anxiety", color: "#F87171" },
  { id: "relationships", label: "relationships", color: "#FB7185" },
  { id: "creativity", label: "creativity", color: "#C084FC" },
];

export const DEFAULT_SETTINGS: AppSettings = {
  coachType: "therapist",
  reminderEnabled: false,
  reminderTime: "20:00",
  theme: "dark",
  appLockEnabled: false,
};

export const MOCK_ENTRIES: JournalEntry[] = [
  {
    id: "seed-1",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    audioUri: "file://seed-1.m4a",
    durationMs: 194000,
    transcript: "Work felt chaotic but I finally closed two priority tasks.",
    refinedTranscript: "Today felt chaotic at work, but I completed two priority tasks and felt relief.",
    summary: [
      "High pressure in the first half of the day.",
      "Completed two priority tasks.",
      "Ended the day with relief.",
    ],
    aiInsight:
      "You respond well to focusing on one priority at a time. Keep protecting your first deep-work block.",
    mood: "anxious",
    tags: ["work", "growth"],
    isFavorite: false,
    isProcessing: false,
  },
  {
    id: "seed-2",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    audioUri: "file://seed-2.m4a",
    durationMs: 142000,
    transcript: "Dinner with family was grounding and made me feel calmer.",
    refinedTranscript: "Family dinner felt grounding and helped me feel calmer.",
    summary: ["Family time felt restorative.", "Anxiety reduced.", "Ended with gratitude."],
    aiInsight: "Connection seems to regulate your stress quickly. Keep this ritual protected.",
    mood: "grateful",
    tags: ["family", "gratitude"],
    isFavorite: true,
    isProcessing: false,
  },
  {
    id: "seed-3",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
    audioUri: "file://seed-3.m4a",
    durationMs: 210000,
    transcript: "I felt very tired and mentally scattered in the afternoon.",
    refinedTranscript: "I felt mentally scattered and physically tired this afternoon.",
    summary: ["Energy dipped in afternoon.", "Focus was fragmented.", "Needs stronger recovery rhythm."],
    aiInsight: "Your energy dip appears predictable. Consider a no-screen 15 minute reset block post-lunch.",
    mood: "tired",
    tags: ["health", "work"],
    isFavorite: false,
    isProcessing: false,
  },
  {
    id: "seed-4",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    audioUri: "file://seed-4.m4a",
    durationMs: 98000,
    transcript: "Morning walk and sunlight made me feel unexpectedly optimistic.",
    refinedTranscript: "A short morning walk and sunlight significantly improved my mood.",
    summary: ["Movement improved emotional state.", "Optimism increased.", "Simple habits are effective."],
    aiInsight: "Your mood responds quickly to movement and light. Keep this as a non-negotiable starter habit.",
    mood: "happy",
    tags: ["health", "growth"],
    isFavorite: true,
    isProcessing: false,
  },
  {
    id: "seed-5",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    audioUri: "file://seed-5.m4a",
    durationMs: 167000,
    transcript: "I felt frustrated after a hard conversation but glad I stayed honest.",
    refinedTranscript: "A difficult conversation left me frustrated, but I am glad I stayed honest.",
    summary: ["Hard conversation occurred.", "Frustration was present.", "Values-aligned communication maintained."],
    aiInsight: "You prioritized honesty under stress. That is emotional progress worth acknowledging.",
    mood: "angry",
    tags: ["relationships", "growth"],
    isFavorite: false,
    isProcessing: false,
  },
  {
    id: "seed-6",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    audioUri: "file://seed-6.m4a",
    durationMs: 118000,
    transcript: "Overall today was okay, nothing huge, just steady progress.",
    refinedTranscript: "Today felt stable overall, with small steady progress.",
    summary: ["No major emotional spikes.", "Steady progress observed.", "Baseline mood remained neutral."],
    aiInsight: "Consistency days are foundational. They build resilience even when they feel uneventful.",
    mood: "neutral",
    tags: ["work", "gratitude"],
    isFavorite: false,
    isProcessing: false,
  },
];
